import type { JornadaRuleInput } from "./types";

export const DEFAULT_JORNADA_RULES: JornadaRuleInput[] = [
  {
    duracaoMinutos: 240,
    nome: "Jornada de 04:00",
    horasSemanais: 24,
    horasMensais: 120,
    intervaloMin: 0,
    intervaloMax: 0,
    limitePeriodoMinutos: 240,
    diasValidos: ["util"],
    active: true,
  },
  {
    duracaoMinutos: 350,
    nome: "Jornada de 05:50",
    horasSemanais: 35,
    horasMensais: 175,
    intervaloMin: 15,
    intervaloMax: 15,
    limitePeriodoMinutos: 240,
    diasValidos: ["util"],
    active: true,
  },
  {
    duracaoMinutos: 440,
    nome: "Jornada de 07:20",
    horasSemanais: 44,
    horasMensais: 220,
    intervaloMin: 60,
    intervaloMax: 120,
    limitePeriodoMinutos: 240,
    diasValidos: ["util"],
    active: true,
  },
  {
    duracaoMinutos: 480,
    nome: "Jornada de 08:00",
    horasSemanais: 44,
    horasMensais: 220,
    intervaloMin: 60,
    intervaloMax: 120,
    limitePeriodoMinutos: 240,
    diasValidos: ["util"],
    active: true,
  },
  {
    duracaoMinutos: 240,
    nome: "Complemento de Sábado 04:00",
    horasSemanais: 44,
    horasMensais: 220,
    intervaloMin: 0,
    intervaloMax: 0,
    limitePeriodoMinutos: 240,
    diasValidos: ["sabado"],
    active: true,
  },
];

export const JORNADA_CONFIG = {
  periodoMaximoHoras: 10,
  interjornadaMinimaMinutos: 660,
  limitePeriodoPadraoMinutos: 240,
  complementoSabadoMinutos: 240,
};
