import type { JornadaRuleInput } from "./types";

export const DEFAULT_JORNADA_RULES: JornadaRuleInput[] = [
  {
    duracaoMinutos: 240,
    nome: "Jornada Parcial 04:00",
    horasSemanais: 24,
    horasMensais: 120,
    intervaloMin: 0,
    intervaloMax: 0,
    diasValidos: ["util", "sabado"],
    active: true,
  },
  {
    duracaoMinutos: 260,
    nome: "Jornada de 04:20",
    horasSemanais: 26,
    horasMensais: 130,
    intervaloMin: 60,
    intervaloMax: 120,
    diasValidos: ["util"],
    active: true,
  },
  {
    duracaoMinutos: 300,
    nome: "Jornada de 05:00",
    horasSemanais: 30,
    horasMensais: 150,
    intervaloMin: 60,
    intervaloMax: 120,
    diasValidos: ["util"],
    active: true,
  },
  {
    duracaoMinutos: 350,
    nome: "Jornada Reduzida 05:50",
    horasSemanais: 35,
    horasMensais: 175,
    intervaloMin: 60,
    intervaloMax: 120,
    diasValidos: ["util"],
    active: true,
  },
  {
    duracaoMinutos: 360,
    nome: "Jornada de 06:00",
    horasSemanais: 36,
    horasMensais: 180,
    intervaloMin: 60,
    intervaloMax: 120,
    diasValidos: ["util"],
    active: true,
  },
  {
    duracaoMinutos: 440,
    nome: "Jornada de 07:20",
    horasSemanais: 44,
    horasMensais: 220,
    intervaloMin: 60,
    intervaloMax: 120,
    diasValidos: ["util", "sabado"],
    active: true,
  },
  {
    duracaoMinutos: 480,
    nome: "Jornada de 08:00",
    horasSemanais: 44,
    horasMensais: 220,
    intervaloMin: 60,
    intervaloMax: 120,
    diasValidos: ["util"],
    active: true,
  },
];

export const JORNADA_CONFIG = {
  periodoMaximoHoras: 10,
  interjornadaMinimaMinutos: 660,
  periodoMaximoSemIntervaloMinutos: 240,
  intervaloAlmocoMinimoMinutos: 60,
};
