services:
  app:
    networks:
      default:
      npm-proxy:
        aliases:
          - perfectutilitares

networks:
  npm-proxy:
    external: true
    name: ${NPM_NETWORK:-nginx-proxy-manager_default}
